import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 1
y = 3

# Many of these are only viable in a floating window manager like Gnome.
[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "M"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Super|Shift"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"
