mv ~/.bashrc ~/.bashrc.bak
mv ~/.bash_profile ~/.bash_profile.bak
stow -v -R -t ~ alacritty
stow -v -R -t ~ autorandr
stow -v -R -t ~ backgrounds
stow -v -R -t ~ bash
stow -v -R -t ~ bat
stow -v -R -t ~ feh
stow -v -R -t ~ flameshot
stow -v -R -t ~ git
stow -v -R -t ~ gtk-3.0
stow -v -R -t ~ i3
stow -v -R -t ~ i3status-rust
stow -v -R -t ~ kitty
stow -v -R -t ~ lf
stow -v -R -t ~ mpv
stow -v -R -t ~ mutt
stow -v -R -t ~ nvim
stow -v -R -t ~ picom
stow -v -R -t ~ readline
stow -v -R -t ~ rmpc
stow -v -R -t ~ rofi
stow -v -R -t ~ screenlayout
stow -v -R -t ~ starship
stow -v -R -t ~ sway
stow -v -R -t ~ tig
stow -v -R -t ~ tmux
stow -v -R -t ~ x
stow -v -R -t ~ xdg
stow -v -R -t ~ yazi
stow -v -R -t ~ zathura
stow -v -R -t ~ local-bin
