icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
# [theme.overrides]
# idle_bg = "#1e1e2e"
# idle_fg = "#f5e0dc"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "custom"
command = "echo '\uf0f4' `xset -q | grep 'DPMS is' | awk '{ print $3 }'`" # assumes fontawesome icons
[[block.click]]
button = "left"
cmd = "sh ~/.dotfiles/scripts/caffeine.sh"

# [[block]]
# block = "custom"
# # set variable CITY in ~/.xsessionrc
# command = "echo $(curl wttr.in/~${CITY}?format=2)"
# interval = 360
# [[block.click]]
# button = "left"
# cmd = "urxvt -hold -e curl wttr.in/~${CITY}"

# Syncthing
[[block]]
block = "custom"
command = "if pgrep -x \"syncthing\" > /dev/null; then echo '{\"icon\":\"\",\"state\":\"Info\", \"text\": \"\"}'; else echo '{\"icon\":\"\",\"state\":\"Warning\", \"text\": \"\"}'; fi"
json = true
[[block.click]]
button = "left"
cmd = "xdg-open http://localhost:8384"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"
missing_format = ""

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %I:%M') "
[[block.click]]
button = "left"
cmd = "urxvt -hold -e calcurse"
