#!/bin/bash

# Copy last commit message copied to clipboard
if [ $(uname) == "Darwin" ]; then
  git log --pretty=format:"%s %n%b" -1 HEAD | pbcopy
fi

if [ $(uname) == "Linux" ]; then
  git log --pretty=format:"%s %n%b" -1 HEAD | xclip -sel c
fi
